#!/bin/sh
case $1 in
"install")
opkg update

cat > /root/auto <<\EOF
#!/bin/sh
ipwan=$(ifconfig | grep -A 2 'wlan0' | awk '/inet addr/{print substr($2,6)}')
mac=$(ifconfig | grep -A 1 'wlan0' | awk '/^[a-z]/ { mac=$NF; next } /inet addr:/ { print mac }')
cok='cookie.txt'
user=$(uci get auto.setting.user)
pass=$(uci get auto.setting.pass)
gwid=$(uci get auto.setting.gw_id)

function login(){
	curl -s -X POST \
		--url 'https://welcome2.wifi.id/authnew/login/check_login.php?ipc='$ipwan'&gw_id='$gwid'&mac='$mac'&redirect=&wlan=GSGSK00715/TLK-WI32358556-0001:@wifi.id' \
		-H 'Host: welcome2.wifi.id' \
		-H 'Accept: application/json, text/javascript, */*; q=0.01' \
		-H 'dnt: 1' \
		-H 'X-Requested-With: XMLHttpRequest' \
		-H 'User-Agent: Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36' \
		-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
		-H 'Origin: https://welcome2.wifi.id' \
		-H 'Sec-Fetch-Site: same-origin' \
		-H 'Sec-Fetch-Mode: cors' \
		-H 'Sec-Fetch-Dest: empty' \
		-H 'Referer: https://welcome2.wifi.id/login/?gw_id='$gwid'&client_mac='$mac'&wlan=GSGSK00715/TLK-WI32358556-0001:@wifi.id&sessionid=' \
		-H 'Accept-Encoding: gzip, deflate, br' \
		-H 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7' \
		-d 'username='$user'&password='$pass'&landURL=' \
		--cookie-jar $cok -b $cok
}

function logout(){
	curl -sL -X POST \
		--url 'https://welcome2.wifi.id/authnew/logout/logoutx.php' \
		-H 'Host: welcome2.wifi.id' \
		-H 'Accept: application/json, text/javascript, */*; q=0.01' \
		-H 'X-Requested-With: XMLHttpRequest' \
		-H 'User-Agent: Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36' \
		-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
		-H 'Origin: https://logout.wifi.id' \
		-H 'Referer: https://logout.wifi.id' \
		-H 'Accept-Encoding: gzip, deflate, br' \
		-H 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7' \
		--cookie-jar $cok -b $cok
}

for i in {1..5}
do
	logout
	curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
	if [[ $? -eq 0 ]]; then
		echo "Logout Gagal ..."
		logger "Logout Gagal ..."
	else
		echo "Logout Sukses ..."
		logger "Logout Sukses ..."
		sleep 5
		break
	fi
done

for i in {1..5}
do
	login
	curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
	if [[ $? -eq 0 ]]; then
		echo "Login Sukses ..."
		logger "Login Sukses ..."
		break
	else
		echo "Login Gagal ..."
		logger "Login Gagal ..."
		sleep 1
	fi
done
rm $cok

EOF

cat > /etc/config/auto << END
config global 'setting'
	option user 'xxxxxxxxxx@gmail.com@com.smartbisnis'
	option pass 'xxxxxxxxxx'
	option gw_id 'XXX-XX-XXX'
	   
END

cat > /www/cgi-bin/auto << END
#!/bin/sh
echo "Content-type: text/html"
echo ""
echo "
<html>
<style type=\"text/css\">

/***************************************
TUBUH
***************************************/
body {
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
	background: #2f2f2f;
	/*
	background-repeat:no-repeat;
	background: -webkit-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: -moz-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: -ms-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: -o-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background-position: fixed;
	background-attachment: fixed;
	background-repeat: center;*/
	margin: 0;
	width: 100%;
	height: auto;
	text-align:center;
	font-family: "Iceland";
	font-size: small;
}
/***************************************
FOOTER LINK
***************************************/
.footer{
	font-size:small;
	margin-top: 10px;
	min-height: 30px;
	max-height: 35px;
	position: fixed; 
	display:block;
	bottom:0%;
	width:100%;
	padding:5px;
	background-color: #2F2F2F;
}
/* unvisited link */
.footer a:link {
	color: white;
}

/* visited link */
.footer a:visited {
	color: white;
}

/* mouse over link */
.footer a:hover {
	color: #04A4D5;
}

/* selected link */
.footer a:active {
	color: white;
}
/***************************************
MAIN BOX
***************************************/
.main-box {
	transition: all 1.0s ease;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
	background-color: rgba(255,255,255,0.5);
	max-width:400px;
	min-width:300px;
	height:auto;
	margin-left: auto ;
	margin-right: auto ;
	margin-bottom:70px;
	padding:10px;
	border: 1px solid #41DA34;
	display: inline-block;
	word-wrap: break-word;
}
.header{
	width: 100%;
	height: auto;
	background-color: #071c4d;
	display: inline-block;
	-webkit-box-shadow: 2px 2px 4px 2px #000000;
	box-shadow: 2px 2px 4px 2px #000000;
}
.img-header{
	margin-top:20px;
	margin-bottom:20px;
}
/***************************************
LABEL/INPUT
***************************************/
.label {
	text-align: left;
	font-family: "Iceland";
	color: #E30014;
	font-size: 13px;
 }
.text {
	width: 100%;
	height: 28px;
	font-family: "Iceland";
	font-size: 13px;
	border: 1px solid #41DA34;
	border-radius: 4px;
 }
.button{
	display: inline-block;
	padding: 10px 25px;
	font-family: "Iceland";
	font-size: 14px;
	text-align: center;
	color: #43DB00;
	background-color: #131510;
	border: 1px solid #41DA34;
	border-radius: 4px;
}
pre {
	text-align: left;
 }

</style>
<head>
<title>Auto Login @Wifi.id</title>
<meta name='viewport' content='width=device-width; initial-scale=1;' />
<link rel='shortcut icon' type='image/png' href='https://cdn.imgbin.com/12/9/21/imgbin-t-shirt-slipknot-logo-music-t-shirt-bV4KjPWuctJNw8JDQ82uEh39c.jpg'>
<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />
</head>
<body>
<link href="https://fonts.googleapis.com/css?family=Iceland" rel='stylesheet' type='text/css'>
</div>
<div class='img-header'>
<a href='/'><img src='https://xblast.com/prank/wp-admin/includes/classs.png' width='250px' height='auto'></a>
</div>
"
USER=\$(uci get auto.setting.user)
PASS=\$(uci get auto.setting.pass)
GW=\$(uci get auto.setting.gw_id)

get_post(){
	for qr in \$QUERY_STRING
	do
	if [ "\${qr%%=*}" == "\$1" ];then
		echo \${qr##*=}| sed 's/+/ /g'
		break
	fi 
	done  
}
if [ "\$REQUEST_METHOD" = POST ]; then
	read -t 3 QUERY_STRING
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/&/ /g') 
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/%3A/:/g')
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/%40/@/g')
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/%3F/?/g')
	
	if [ "\$(get_post update)" == "Update Config" ]; then
		USER=\$(get_post user)
		PASS=\$(get_post pass)
		GW=\$(get_post gw_id)
		uci set auto.setting.user=\$USER
		uci set auto.setting.pass=\$PASS
		uci set auto.setting.gw_id=\$GW
		uci commit auto
	fi
fi
echo "<div class=main-box>
<h1><font size='5' color='#E30014'>Auto Login @Wifi.id</font></h1>
<h3><font size='3' color='#41DA34'>-=[ OpenWrt ]=-</font></h3>
<form method=\"post\">       
<div class=label>Username :</div><input name=\"user\" class=text value=\"\$USER\"><br>
<div class=label>Password :</div><input name=\"pass\" class=text value=\"\$PASS\"><br>
<div class=label>GW ID :</div><input name=\"gw_id\" class=text value=\"\$GW\"><br><br>
<input type=\"submit\" class=\"button\" name=\"update\" value=\"Update Config\">
        

</form><hr>
	"
echo "<pre>"
echo "</pre>
<p> NB. Tambahkan Schedule di router & restart cron </br>
( */10 * * * * sh /root/auto ) </p>
</div>
<div class='footer'>
&copy <font color='#41DA43'>Idra Psyco</font> - <font color='#E30014'>OpenWrt</font>
</div>
</body></html>"

END
sleep 1
chmod 755 /www/cgi-bin/auto
chmod 755 auto
echo "install auto login selesai"
echo "akses konfigurasi di http://ipserver//cgi-bin/auto"
echo "Script Auto Login @Wifi.id By Idra CakepZ"
rm -rf autologin
exit 0
;;
esac
#end
