#!/bin/sh
case $1 in
"install")
opkg update

cat > /root/cek << EOF
#!/bin/sh
ipwan=\$(ifconfig | grep -A 2 'wlan0' | awk '/inet addr/{print substr(\$2,6)}')
mac=\$(ifconfig | grep -A 1 'wlan0' | awk '/^[a-z]/ { mac=\$NF; next } /inet addr:/ { print mac }')
cok='cookie.txt'
user1=\$(uci get auto.setting.user1)
user2=\$(uci get auto.setting.user2)
pass1=\$(uci get auto.setting.pass1)
pass2=\$(uci get auto.setting.pass2)
gwid=\$(uci get auto.setting.gw_id)

function login(){
	curl -s -X POST \
		--url 'https://welcome2.wifi.id/authnew/login/check_login.php?ipc='\$ipwan'&gw_id='\$gwid'&mac='\$mac'&redirect=&wlan=' \
		-H 'Host: welcome2.wifi.id' \
		-H 'Accept: application/json, text/javascript, */*; q=0.01' \
		-H 'dnt: 1' \
		-H 'X-Requested-With: XMLHttpRequest' \
		-H 'User-Agent: Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36' \
		-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
		-H 'Origin: https://welcome2.wifi.id' \
		-H 'Sec-Fetch-Site: same-origin' \
		-H 'Sec-Fetch-Mode: cors' \
		-H 'Sec-Fetch-Dest: empty' \
		-H 'Referer: https://welcome2.wifi.id/login/?gw_id='\$gwid'&client_mac='\$mac'&wlan=&sessionid=' \
		-H 'Accept-Encoding: gzip, deflate, br' \
		-H 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7' \
		-d 'username='\$1'&password='\$2'&landURL=' \
		--cookie-jar \$cok -b \$cok
}

for i in 1 2 3 4 5 6 7 8 9 10
do
	curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
	if [[ \$? -eq 0 ]]; then
		echo "Connected ..."
		logger "Connected ..."
		break
	else
		echo "Login Akun 1"
		logger "Login Akun 1"
		login \$user1 \$pass1
		sleep 5
                rm \$cok
		curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
		if [[ \$? -eq 0 ]]; then
			echo "Connected ..."
			logger "Connected ..."
			break
		else
			echo "Login Akun 2"
			logger "Login Akun 2"
			login \$user2 \$pass2
			sleep 5
                        rm \$cok
		fi
	fi
done

EOF


cat > /root/auto << EOF
#!/bin/sh
ipwan=\$(ifconfig | grep -A 2 'wlan0' | awk '/inet addr/{print substr(\$2,6)}')
mac=\$(ifconfig | grep -A 1 'wlan0' | awk '/^[a-z]/ { mac=\$NF; next } /inet addr:/ { print mac }')
cok='cookie.txt'
user1=\$(uci get auto.setting.user1)
user2=\$(uci get auto.setting.user2)
pass1=\$(uci get auto.setting.pass1)
pass2=\$(uci get auto.setting.pass2)
gwid=\$(uci get auto.setting.gw_id)

function login(){
	curl -s -X POST \
		--url 'https://welcome2.wifi.id/authnew/login/check_login.php?ipc='\$ipwan'&gw_id='\$gwid'&mac='\$mac'&redirect=&wlan=' \
		-H 'Host: welcome2.wifi.id' \
		-H 'Accept: application/json, text/javascript, */*; q=0.01' \
		-H 'X-Requested-With: XMLHttpRequest' \
		-H 'User-Agent: Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36' \
		-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
		-H 'Origin: https://welcome2.wifi.id' \
		-H 'Sec-Fetch-Site: same-origin' \
		-H 'Sec-Fetch-Mode: cors' \
		-H 'Sec-Fetch-Dest: empty' \
		-H 'Referer: https://welcome2.wifi.id/login/?gw_id='\$gwid'&client_mac='\$mac'&wlan=&sessionid=' \
		-H 'Accept-Encoding: gzip, deflate, br' \
		-H 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7' \
		-d 'username='\$1'&password='\$2'&landURL=' \
		--cookie-jar \$cok -b \$cok
}

function logout(){
    curl -sL -X POST \
        --url 'https://welcome2.wifi.id/authnew/logout/logoutx.php' \
        -H 'Host: welcome2.wifi.id' \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'X-Requested-With: XMLHttpRequest' \
        -H 'User-Agent: Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36' \
        -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
        -H 'Origin: https://logout.wifi.id' \
        -H 'Referer: https://logout.wifi.id' \
        -H 'Accept-Encoding: gzip, deflate, br' \
        -H 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7' \
        --cookie-jar \$cok -b \$cok
}

for i in 1 2 3 4 5 6 7 8 9 10
do
	logout
	curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
	if [[ \$? -eq 0 ]]; then
		echo "Logout Gagal ..."
		logger "Logout Gagal ..."
	else
		echo "Logout Sukses ..."
		logger "Logout Sukses ..."
		sleep 10
		break
	fi
done

for i in 1 2 3 4 5 6 7 8 9 10
do
	echo "Login Akun 1"
	logger "Login Akun 1"
	login \$user1 \$pass1
        rm \$cok
	curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
	if [[ \$? -eq 0 ]]; then
		echo "Login Sukses ..."
		logger "Login Sukses ..."
		break
	else
		echo "Login Gagal ..."
		logger "Login Gagal ..."
		echo "Login Akun 2"
		logger "Login Akun 2"
		sleep 5
		login \$user2 \$pass2
                rm \$cok
		curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
		if [[ \$? -eq 0 ]]; then
			echo "Login Sukses ..."
			logger "Login Sukses ..."
			break
		else
			echo "Login Gagal ..."
			logger "Login Gagal ..."
			sleep 5
		fi
	fi
done

EOF

cat > /etc/config/auto << END
config global 'setting'
	option user1 'xxxxxxxxxx@gmail.com@com.smartbisnis'
	option pass1 'xxxxxxxxxx'
	option user2 'xxxxxxxxxx@gmail.com@com.smartbisnis'
	option pass2 'xxxxxxxxxx'
	option gw_id 'XXX-XX-XXX'
	   
END

cat > /www/cgi-bin/auto << END
#!/bin/sh
echo "Content-type: text/html"
echo ""
echo "
<html>
<style type=\"text/css\">
/***************************************
TUBUH
***************************************/
body {
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
	background: #2f2f2f;
	/*
	background-repeat:no-repeat;
	background: -webkit-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: -moz-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: -ms-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: -o-linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background: linear-gradient( to bottom, #19405c, #769ec3, #c6d6e6);
	background-position: fixed;
	background-attachment: fixed;
	background-repeat: center;*/
	margin: 0;
	width: 100%;
	height: auto;
	text-align: center;
	font-family: "Iceland";
	font-size: small;
}
/***************************************
FOOTER LINK
***************************************/
.footer{
	font-size: small;
	margin-top: 10px;
	min-height: 25px;
	max-height: 30px;
	position: fixed; 
	display: block;
	bottom: 0%;
	width: 100%;
	padding: 5px;
	background-color: #2F2F2F;
}
/* unvisited link */
.footer a:link {
	color: white;
}

/* visited link */
.footer a:visited {
	color: white;
}

/* mouse over link */
.footer a:hover {
	color: #04A4D5;
}

/* selected link */
.footer a:active {
	color: white;
}
/***************************************
MAIN BOX
***************************************/
.main-box {
	transition: all 1.0s ease;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	border-radius: 5px;
	background-color: rgba(255,255,255,0.5);
	max-width: 400px;
	min-width: 300px;
	height: auto;
	margin-left: auto ;
	margin-right: auto ;
	margin-bottom: 70px;
	padding: 10px;
	border: 1px solid #41DA34;
	display: inline-block;
	word-wrap: break-word;
}
.header{
	width: 100%;
	height: auto;
	background-color: #071c4d;
	display: inline-block;
	-webkit-box-shadow: 2px 2px 4px 2px #000000;
	box-shadow: 2px 2px 4px 2px #000000;
}
.img-header{
	margin-top: 10px;
	margin-bottom: 10px;
	margin-left: auto;
	margin-right: auto;
	width: 252px;
	height: auto;
	border: 1px solid #E30014;
	border-radius: 4px;
}
/***************************************
LABEL/INPUT
***************************************/
.label {
	margin-left : 10px;
	text-align: left;
	font-family: "Iceland";
	color: #E30014;
	font-size: 14px;
}
.text {
	width: 92%;
	height: 28px;
	font-family: "Iceland";
	font-size: 14px;
	border: 1px solid #41DA34;
	border-radius: 4px;
	padding-left: 4px;
}
.textp {
	margin-left: 4px;
	width: 86%;
	height: 28px;
	font-family: "Iceland";
	font-size: 14px;
	border: 1px solid #41DA34;
	border-radius: 4px;
	padding-left: 4px;
}
.gwid {
	float: left;
	margin-left: 12px;
	width: auto;
	height: auto;
	font-family: "Iceland";
	font-size: 14px;
	border: 1px solid #41DA34;
	border-radius: 4px;
}
.button {
	display: inline-block;
	padding: 10px 25px;
	font-family: "Iceland";
	font-size: 15px;
	text-align: center;
	color: #E30014;
	background-color: #2f2f2f;
	border: 1px solid #41DA34;
	border-radius: 4px;
}
pre {
	text-align: left;
}
/***************************************
RESULT KONEKSI
***************************************/
.status {
	text-align: center;
	font-family: "Iceland";
	color: #E30014;
	font-size: 15px;
}
.stats {
	width: 70%;
	height: 30px;
	font-family: "Iceland";
	font-size: 14px;
	text-align: center;
	color: #43DB00;
	border: 1px solid #41DA34;
	border-radius: 4px;
}

</style>
<head>
<title>Auto Login @Wifi.id</title>
<meta name='viewport' content='width=device-width; initial-scale=1;' />
<link rel='shortcut icon' type='image/png' href='https://cdn.imgbin.com/12/9/21/imgbin-t-shirt-slipknot-logo-music-t-shirt-bV4KjPWuctJNw8JDQ82uEh39c.jpg'>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
</head>
<body>
<link href="https://fonts.googleapis.com/css?family=Iceland" rel='stylesheet' type='text/css'>
</div>
<div class='img-header'>
<a href='/'><img src='https://xblast.com/prank/wp-admin/includes/classs.png' width='250px' height='auto'></a>
</div>
"
USER1=\$(uci get auto.setting.user1)
PASS1=\$(uci get auto.setting.pass1)
USER2=\$(uci get auto.setting.user2)
PASS2=\$(uci get auto.setting.pass2)
GWID=\$(uci get auto.setting.gw_id)
if [ "\$GWID" == "WAG-D1-TLK" ]; then
	GWID="WAG-D1-TLK"
elif [ "\$GWID" == "WAG-D1-PBR" ]; then
	GWID="WAG-D1-PBR"
elif [ "\$GWID" == "WAG-D2-JT" ]; then
	GWID="WAG-D2-JT"
elif [ "\$GWID" == "WAG-D2-CKA" ]; then
	GWID="WAG-D2-CKA"
elif [ "\$GWID" == "WAG-D3-CBN" ]; then
	GWID="WAG-D3-CBN"
elif [ "\$GWID" == "WAG-D3-LBG" ]; then
	GWID="WAG-D3-LBG"
elif [ "\$GWID" == "WAG-D4-KBU" ]; then
	GWID="WAG-D4-KBU"
elif [ "\$GWID" == "WAG-D4-GBL" ]; then
	GWID="WAG-D4-GBL"
elif [ "\$GWID" == "WAG-D5-KBL" ]; then
	GWID="WAG-D5-KBL"
else
	GWID="WAG-D5-KBL"
fi
CEK=\$(curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null)
if [[ \$? -eq 0 ]]; then
	STATS="Connected... !!!"
else
	STATS="Koneksi Terputus... !!!"
fi

get_post(){
	for qr in \$QUERY_STRING
	do          
	if [ "\${qr%%=*}" == "\$1" ];then              
		echo \${qr##*=}| sed 's/+/ /g' 
		break
	fi 
 done  
}
if [ "\$REQUEST_METHOD" = POST ]; then
	read -t 3 QUERY_STRING
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/&/ /g') 
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/%3A/:/g')
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/%40/@/g')
	QUERY_STRING=\$(echo \$QUERY_STRING | sed 's/%3F/?/g')
            
	if [ "\$(get_post update)" == "Update Config" ]; then
		USER1=\$(get_post user1)
		PASS1=\$(get_post pass1)
		USER2=\$(get_post user2)
		PASS2=\$(get_post pass2)
		GWID=\$(get_post gw_id)
		uci set auto.setting.user1=\$USER1
		uci set auto.setting.pass1=\$PASS1
		uci set auto.setting.user2=\$USER2
		uci set auto.setting.pass2=\$PASS2
		uci set auto.setting.gw_id=\$GWID
		uci commit auto
	fi
fi
echo "<div class=main-box>
<h1><font size='5' color='#E30014'>AUTO LOGIN @Wifi.Id</font></h1>
<h3><font size='3' color='#41DA43'>-=[ DOUBLE AKUN ]=-</font></h3>
<form method=\"post\">       
<div class=label>Username 1 :</div><input type=\"text\" id=\"user1\" name=\"user1\" class=\"text\" value=\"\$USER1\"><br>
<div class=label>Password 1 :</div><input type=\"password\" id=\"pass1\" name=\"pass1\" class=\"textp\" value=\"\$PASS1\"><input type=\"checkbox\" onclick=\"myPASS1()\"><br><br>
<div class=label>Username 2 :</div><input type=\"text\" id=\"user1\" name=\"user2\" class=\"text\" value=\"\$USER2\"><br>
<div class=label>Password 2 :</div><input type=\"password\" id=\"pass2\" name=\"pass2\" class=\"textp\" value=\"\$PASS2\"><input type=\"checkbox\" onclick=\"myPASS2()\"><br><br>
<div class=label>GW ID :</div>
<div class=\"gwid\"><select id=\"gwid\" name=\"gwid\">
<option value=\"\$GWID\">\$GWID</option>
<option value=\"WAG-D1-TLK\">WAG-D1-TLK</option>
<option value=\"WAG-D1-PBR\">WAG-D1-PBR</option>
<option value=\"WAG-D2-JT\">WAG-D2-JT</option>
<option value=\"WAG-D2-CKA\">WAG-D2-CKA</option>
<option value=\"WAG-D3-CBN\">WAG-D3-CBN</option>
<option value=\"WAG-D3-LBG\">WAG-D3-LBG</option>
<option value=\"WAG-D4-KBU\">WAG-D4-KBU</option>
<option value=\"WAG-D4-GBL\">WAG-D4-GBL</option>
<option value=\"WAG-D5-KBL\">WAG-D5-KBL</option>
</select></div><br><br><br>
<input type=\"submit\" class=\"button\" name=\"update\" value=\"Update Config\">
        

</form><hr>
	"
echo "<pre>"
echo "</pre>
<div class='status'>-=[ STATUS KONEKSI ]=-</div><br><input type=\"text\" name=\"stats\" class=\"stats\" value=\"\$STATS\"><br>
</div>
<div class='footer'>
&copy <font color='#41DA43'>Idra Psyco</font> - <font color='#E30014'>OpenWrt</font>
</div>
<script>
function myPASS1() {var x = document.getElementById(\"pass1\");if (x.type === \"password\"){x.type=\"text\";}else {x.type = \"password\";}}
function myPASS2() {var y = document.getElementById(\"pass2\");if (y.type === \"password\"){y.type=\"text\";}else {y.type = \"password\";}}
</script>
</body></html>"

END

cat > /etc/crontabs/root << END
5 */8 * * * sh /root/auto
*/15 * * * * sh /root/cek
5 4 * * * sleep 60 && touch /etc/banner && reboot
END

/etc/init.d/cron restart
sleep 1
chmod 755 /www/cgi-bin/auto
chmod 755 /root/auto
chmod 755 /root/cek
echo "install auto login selesai"
echo "akses konfigurasi di http://ipserver//cgi-bin/auto"
echo "Script Auto Login @Wifi.id By Idra CakepZ"
rm -rf double
  exit 0
;;
esac
#end
