#!/bin/sh

for i in 1 2 3 4 5
do
	curl -s --connect-timeout 5 'https://www.google.com' &> /dev/null
	if [[ $? -eq 0 ]]; then
		echo "Connected ..."
		logger "Connected ..."
		break
	else
		echo "Refresh Ip ..."
		logger "Refresh Ip ..."
		ifconfig wlan0 down
		sleep 15
		ifconfig wlan0 up
	fi
done
